import Head from 'next/head';
import Contacts from '../views/Contacts';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

export default function ImpressumPage() {
  return (
    <>
      <Head>
        <title>Automatum | Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Contacts />
    </>
  )
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])), 
    },
  };
}
