import Head from 'next/head';
import Home from '../views/Home';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

export default function HomePage () {
  return (
    <>
      <Head>
        <title>Automatum | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  )
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'home'])), 
    },
  };
}
